version: '2'
services:
  seed_node:
    image: 'datastax/dse-server:5.1.11'
    environment:
      - DS_LICENSE=accept
  node:
    image: 'datastax/dse-server:5.1.11'
    environment:
      - DS_LICENSE=accept
      - SEEDS=seed_node
    links:
      - seed_node
