version: '3'

services:
  product-service:
    build: ./product
    volumes:
      - ./product:/usr/src/app
    ports:
      - 5001:80

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: moje-heslo
     MYSQL_DATABASE: moje-databaze
     MYSQL_USER:  muj-user
     MYSQL_PASSWORD:  moje-heslo

  website:
    build: ./website
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - product-service
      - db

volumes:
    db_data:
